name: Generate Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: "59 1 * * *"   # daily at 01:59 UTC

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: asset/base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

  languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: asset/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14

  # habits:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: lowlighter/metrics@latest
  #       with:
  #         filename: asset/habits.svg
  #         token: ${{ secrets.METRICS_TOKEN }}
  #         base: ""
  #         plugin_habits: yes
  #         plugin_habits_facts: yes
  #         plugin_habits_charts: yes
  #         plugin_habits_from: 200

  # activity:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: lowlighter/metrics@latest
  #       with:
  #         filename: asset/activity.svg
  #         token: ${{ secrets.METRICS_TOKEN }}
  #         base: ""
  #         plugin_activity: yes
  #         plugin_activity_limit: 5
  #         plugin_activity_days: 14

  isocalendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: asset/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  # achievements:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: lowlighter/metrics@latest
  #       with:
  #         filename: asset/achievements.svg
  #         token: ${{ secrets.METRICS_TOKEN }}
  #         base: ""
  #         plugin_achievements: yes
  #         plugin_achievements_threshold: C

  # projects:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: lowlighter/metrics@latest
  #       with:
  #         filename: asset/projects.svg
  #         token: ${{ secrets.METRICS_TOKEN }}
  #         base: ""
  #         plugin_projects: yes

  stargazers:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: asset/stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: yes